name: goldentest
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

scripts:
  goldentest: flutter test --update-goldens --tags=golden
  goldentest_compare: flutter test --tags=golden
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  golden_toolkit: ^0.13.0

flutter:
  uses-material-design: true
